# Generated by Django 4.0.3 on 2022-04-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_categories_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('mobile', models.IntegerField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
